// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

package com.largehat.common.im.packets;

/**
 * <pre>
 *协议类型
 * </pre>
 *
 * Protobuf enum {@code AgreementType}
 */
public enum AgreementType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *socket
   * </pre>
   *
   * <code>AGREEMENT_TYPE_SOCKET = 0;</code>
   */
  AGREEMENT_TYPE_SOCKET(0),
  /**
   * <pre>
   *webSocket
   * </pre>
   *
   * <code>AGREEMENT_TYPE_WEBSOCKET = 1;</code>
   */
  AGREEMENT_TYPE_WEBSOCKET(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *socket
   * </pre>
   *
   * <code>AGREEMENT_TYPE_SOCKET = 0;</code>
   */
  public static final int AGREEMENT_TYPE_SOCKET_VALUE = 0;
  /**
   * <pre>
   *webSocket
   * </pre>
   *
   * <code>AGREEMENT_TYPE_WEBSOCKET = 1;</code>
   */
  public static final int AGREEMENT_TYPE_WEBSOCKET_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static AgreementType valueOf(int value) {
    return forNumber(value);
  }

  public static AgreementType forNumber(int value) {
    switch (value) {
      case 0: return AGREEMENT_TYPE_SOCKET;
      case 1: return AGREEMENT_TYPE_WEBSOCKET;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AgreementType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AgreementType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AgreementType>() {
          public AgreementType findValueByNumber(int number) {
            return AgreementType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return Chat.getDescriptor()
        .getEnumTypes().get(10);
  }

  private static final AgreementType[] VALUES = values();

  public static AgreementType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AgreementType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:AgreementType)
}

