// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.largehat.common.im.packets;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nchat.proto*f\n\nDeviceType\022\026\n\022DEVICE_TYP" +
      "E_UNKNOW\020\000\022\022\n\016DEVICE_TYPE_PC\020\001\022\027\n\023DEVICE" +
      "_TYPE_ANDROID\020\002\022\023\n\017DEVICE_TYPE_IOS\020\003*b\n\t" +
      "GroupType\022\025\n\021GROUP_TYPE_UNKNOW\020\000\022\024\n\020GROU" +
      "P_TYPE_FIXED\020\001\022\023\n\017GROUP_TYPE_TEMP\020\002\022\023\n\017G" +
      "ROUP_TYPE_CHAT\020\003*\301\004\n\007Command\022\022\n\016COMMAND_" +
      "UNKNOW\020\000\022\031\n\025COMMAND_HANDSHAKE_REQ\020\001\022\032\n\026C" +
      "OMMAND_HANDSHAKE_RESP\020\002\022\024\n\020COMMAND_AUTH_" +
      "REQ\020\003\022\025\n\021COMMAND_AUTH_RESP\020\004\022\025\n\021COMMAND_" +
      "LOGIN_REQ\020\005\022\026\n\022COMMAND_LOGIN_RESP\020\006\022\032\n\026C",
      "OMMAND_JOIN_GROUP_REQ\020\007\022\033\n\027COMMAND_JOIN_" +
      "GROUP_RESP\020\010\022\"\n\036COMMAND_JOIN_GROUP_NOTIF" +
      "Y_RESP\020\t\022\"\n\036COMMAND_EXIT_GROUP_NOTIFY_RE" +
      "SP\020\n\022\024\n\020COMMAND_CHAT_REQ\020\013\022\025\n\021COMMAND_CH" +
      "AT_RESP\020\014\022\031\n\025COMMAND_HEARTBEAT_REQ\020\r\022\025\n\021" +
      "COMMAND_CLOSE_REQ\020\016\022\032\n\026COMMAND_CANCEL_MS" +
      "G_REQ\020\017\022\033\n\027COMMAND_CANCEL_MSG_RESP\020\020\022\030\n\024" +
      "COMMAND_GET_USER_REQ\020\021\022\031\n\025COMMAND_GET_US" +
      "ER_RESP\020\022\022\037\n\033COMMAND_OFFLINE_MESSAGE_REQ" +
      "\020\023\022 \n\034COMMAND_OFFLINE_MESSAGE_RESP\020\024*\320\001\n",
      "\017JoinGroupResult\022\034\n\030JOIN_GROUP_RESULT_UN" +
      "KNOW\020\000\022\030\n\024JOIN_GROUP_RESULT_OK\020\001\022\037\n\033JOIN" +
      "_GROUP_RESULT_NOT_EXIST\020\002\022 \n\034JOIN_GROUP_" +
      "RESULT_GROUP_FULL\020\003\022!\n\035JOIN_GROUP_RESULT" +
      "_IN_BACKLIST\020\004\022\037\n\033JOIN_GROUP_RESULT_TAKE" +
      "OUTED\020\005*M\n\010ChatType\022\024\n\020CHAT_TYPE_UNKNOW\020" +
      "\000\022\024\n\020CHAT_TYPE_PUBLIC\020\001\022\025\n\021CHAT_TYPE_PRI" +
      "VATE\020\002*}\n\007MsgType\022\021\n\rMSG_TYPE_TEXT\020\000\022\020\n\014" +
      "MSG_TYPE_IMG\020\001\022\022\n\016MSG_TYPE_VOICE\020\002\022\022\n\016MS" +
      "G_TYPE_VIDEO\020\003\022\022\n\016MSG_TYPE_MUSIC\020\004\022\021\n\rMS",
      "G_TYPE_NEWS\020\005B\"\n\036com.largehat.common.im." +
      "packetsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
