// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Content.proto

package com.largehat.common.im.packets;

public final class ContentProto {
  private ContentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.largehat.common.im.packets.Content)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *内容信息,如果是MSG_TYPE_TEXT直接读取显示， 如果是MSG_TYPE_IMG, text是地址信息
     * </pre>
     *
     * <code>optional string text = 1;</code>
     */
    String getText();
    /**
     * <pre>
     *内容信息,如果是MSG_TYPE_TEXT直接读取显示， 如果是MSG_TYPE_IMG, text是地址信息
     * </pre>
     *
     * <code>optional string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <pre>
     *宽度
     * </pre>
     *
     * <code>optional int32 width = 2;</code>
     */
    int getWidth();

    /**
     * <pre>
     *高度
     * </pre>
     *
     * <code>optional int32 higth = 3;</code>
     */
    int getHigth();
  }
  /**
   * Protobuf type {@code com.largehat.common.im.packets.Content}
   */
  public  static final class Content extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.largehat.common.im.packets.Content)
      ContentOrBuilder {
    // Use Content.newBuilder() to construct.
    private Content(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Content() {
      text_ = "";
      width_ = 0;
      higth_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Content(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
            case 16: {

              width_ = input.readInt32();
              break;
            }
            case 24: {

              higth_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ContentProto.internal_static_com_largehat_common_im_packets_Content_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ContentProto.internal_static_com_largehat_common_im_packets_Content_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Content.class, Builder.class);
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    private volatile Object text_;
    /**
     * <pre>
     *内容信息,如果是MSG_TYPE_TEXT直接读取显示， 如果是MSG_TYPE_IMG, text是地址信息
     * </pre>
     *
     * <code>optional string text = 1;</code>
     */
    public String getText() {
      Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *内容信息,如果是MSG_TYPE_TEXT直接读取显示， 如果是MSG_TYPE_IMG, text是地址信息
     * </pre>
     *
     * <code>optional string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WIDTH_FIELD_NUMBER = 2;
    private int width_;
    /**
     * <pre>
     *宽度
     * </pre>
     *
     * <code>optional int32 width = 2;</code>
     */
    public int getWidth() {
      return width_;
    }

    public static final int HIGTH_FIELD_NUMBER = 3;
    private int higth_;
    /**
     * <pre>
     *高度
     * </pre>
     *
     * <code>optional int32 higth = 3;</code>
     */
    public int getHigth() {
      return higth_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
      }
      if (width_ != 0) {
        output.writeInt32(2, width_);
      }
      if (higth_ != 0) {
        output.writeInt32(3, higth_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
      }
      if (width_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, width_);
      }
      if (higth_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, higth_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Content)) {
        return super.equals(obj);
      }
      Content other = (Content) obj;

      boolean result = true;
      result = result && getText()
          .equals(other.getText());
      result = result && (getWidth()
          == other.getWidth());
      result = result && (getHigth()
          == other.getHigth());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (37 * hash) + WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + getWidth();
      hash = (37 * hash) + HIGTH_FIELD_NUMBER;
      hash = (53 * hash) + getHigth();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Content parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Content parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Content parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Content parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Content parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Content parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Content parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Content parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Content parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Content parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Content prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.largehat.common.im.packets.Content}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.largehat.common.im.packets.Content)
        ContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ContentProto.internal_static_com_largehat_common_im_packets_Content_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ContentProto.internal_static_com_largehat_common_im_packets_Content_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Content.class, Builder.class);
      }

      // Construct using com.largehat.common.im.packets.ContentProto.Content.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        text_ = "";

        width_ = 0;

        higth_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ContentProto.internal_static_com_largehat_common_im_packets_Content_descriptor;
      }

      public Content getDefaultInstanceForType() {
        return Content.getDefaultInstance();
      }

      public Content build() {
        Content result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Content buildPartial() {
        Content result = new Content(this);
        result.text_ = text_;
        result.width_ = width_;
        result.higth_ = higth_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Content) {
          return mergeFrom((Content)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Content other) {
        if (other == Content.getDefaultInstance()) return this;
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        if (other.getWidth() != 0) {
          setWidth(other.getWidth());
        }
        if (other.getHigth() != 0) {
          setHigth(other.getHigth());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Content parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Content) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object text_ = "";
      /**
       * <pre>
       *内容信息,如果是MSG_TYPE_TEXT直接读取显示， 如果是MSG_TYPE_IMG, text是地址信息
       * </pre>
       *
       * <code>optional string text = 1;</code>
       */
      public String getText() {
        Object ref = text_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *内容信息,如果是MSG_TYPE_TEXT直接读取显示， 如果是MSG_TYPE_IMG, text是地址信息
       * </pre>
       *
       * <code>optional string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *内容信息,如果是MSG_TYPE_TEXT直接读取显示， 如果是MSG_TYPE_IMG, text是地址信息
       * </pre>
       *
       * <code>optional string text = 1;</code>
       */
      public Builder setText(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容信息,如果是MSG_TYPE_TEXT直接读取显示， 如果是MSG_TYPE_IMG, text是地址信息
       * </pre>
       *
       * <code>optional string text = 1;</code>
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容信息,如果是MSG_TYPE_TEXT直接读取显示， 如果是MSG_TYPE_IMG, text是地址信息
       * </pre>
       *
       * <code>optional string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }

      private int width_ ;
      /**
       * <pre>
       *宽度
       * </pre>
       *
       * <code>optional int32 width = 2;</code>
       */
      public int getWidth() {
        return width_;
      }
      /**
       * <pre>
       *宽度
       * </pre>
       *
       * <code>optional int32 width = 2;</code>
       */
      public Builder setWidth(int value) {
        
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *宽度
       * </pre>
       *
       * <code>optional int32 width = 2;</code>
       */
      public Builder clearWidth() {
        
        width_ = 0;
        onChanged();
        return this;
      }

      private int higth_ ;
      /**
       * <pre>
       *高度
       * </pre>
       *
       * <code>optional int32 higth = 3;</code>
       */
      public int getHigth() {
        return higth_;
      }
      /**
       * <pre>
       *高度
       * </pre>
       *
       * <code>optional int32 higth = 3;</code>
       */
      public Builder setHigth(int value) {
        
        higth_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *高度
       * </pre>
       *
       * <code>optional int32 higth = 3;</code>
       */
      public Builder clearHigth() {
        
        higth_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.largehat.common.im.packets.Content)
    }

    // @@protoc_insertion_point(class_scope:com.largehat.common.im.packets.Content)
    private static final Content DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Content();
    }

    public static Content getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Content>
        PARSER = new com.google.protobuf.AbstractParser<Content>() {
      public Content parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Content(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Content> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Content> getParserForType() {
      return PARSER;
    }

    public Content getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_largehat_common_im_packets_Content_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_largehat_common_im_packets_Content_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rContent.proto\022\036com.largehat.common.im." +
      "packets\"5\n\007Content\022\014\n\004text\030\001 \001(\t\022\r\n\005widt" +
      "h\030\002 \001(\005\022\r\n\005higth\030\003 \001(\005B0\n\036com.largehat.c" +
      "ommon.im.packetsB\014ContentProtoH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_largehat_common_im_packets_Content_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_largehat_common_im_packets_Content_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_largehat_common_im_packets_Content_descriptor,
        new String[] { "Text", "Width", "Higth", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
