// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Group.proto

package com.largehat.common.im.packets;

public final class GroupProto {
  private GroupProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.largehat.common.im.packets.Group)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *群ID
     * </pre>
     *
     * <code>optional int32 groupId = 1;</code>
     */
    int getGroupId();

    /**
     * <pre>
     *群组名称
     * </pre>
     *
     * <code>optional string groupName = 2;</code>
     */
    String getGroupName();
    /**
     * <pre>
     *群组名称
     * </pre>
     *
     * <code>optional string groupName = 2;</code>
     */
    com.google.protobuf.ByteString
        getGroupNameBytes();

    /**
     * <pre>
     *群头像
     * </pre>
     *
     * <code>optional string avatar = 3;</code>
     */
    String getAvatar();
    /**
     * <pre>
     *群头像
     * </pre>
     *
     * <code>optional string avatar = 3;</code>
     */
    com.google.protobuf.ByteString
        getAvatarBytes();

    /**
     * <pre>
     *群类型
     * </pre>
     *
     * <code>optional .GroupType groupType = 4;</code>
     */
    int getGroupTypeValue();
    /**
     * <pre>
     *群类型
     * </pre>
     *
     * <code>optional .GroupType groupType = 4;</code>
     */
    GroupType getGroupType();

    /**
     * <pre>
     *归属组织机构
     * </pre>
     *
     * <code>optional int32 orgId = 5;</code>
     */
    int getOrgId();

    /**
     * <pre>
     *最大人数
     * </pre>
     *
     * <code>optional int64 maxNum = 6;</code>
     */
    long getMaxNum();
  }
  /**
   * Protobuf type {@code com.largehat.common.im.packets.Group}
   */
  public  static final class Group extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.largehat.common.im.packets.Group)
      GroupOrBuilder {
    // Use Group.newBuilder() to construct.
    private Group(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Group() {
      groupId_ = 0;
      groupName_ = "";
      avatar_ = "";
      groupType_ = 0;
      orgId_ = 0;
      maxNum_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Group(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              groupId_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              groupName_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              avatar_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              groupType_ = rawValue;
              break;
            }
            case 40: {

              orgId_ = input.readInt32();
              break;
            }
            case 48: {

              maxNum_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GroupProto.internal_static_com_largehat_common_im_packets_Group_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GroupProto.internal_static_com_largehat_common_im_packets_Group_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Group.class, Builder.class);
    }

    public static final int GROUPID_FIELD_NUMBER = 1;
    private int groupId_;
    /**
     * <pre>
     *群ID
     * </pre>
     *
     * <code>optional int32 groupId = 1;</code>
     */
    public int getGroupId() {
      return groupId_;
    }

    public static final int GROUPNAME_FIELD_NUMBER = 2;
    private volatile Object groupName_;
    /**
     * <pre>
     *群组名称
     * </pre>
     *
     * <code>optional string groupName = 2;</code>
     */
    public String getGroupName() {
      Object ref = groupName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        groupName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *群组名称
     * </pre>
     *
     * <code>optional string groupName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGroupNameBytes() {
      Object ref = groupName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        groupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVATAR_FIELD_NUMBER = 3;
    private volatile Object avatar_;
    /**
     * <pre>
     *群头像
     * </pre>
     *
     * <code>optional string avatar = 3;</code>
     */
    public String getAvatar() {
      Object ref = avatar_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *群头像
     * </pre>
     *
     * <code>optional string avatar = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      Object ref = avatar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPTYPE_FIELD_NUMBER = 4;
    private int groupType_;
    /**
     * <pre>
     *群类型
     * </pre>
     *
     * <code>optional .GroupType groupType = 4;</code>
     */
    public int getGroupTypeValue() {
      return groupType_;
    }
    /**
     * <pre>
     *群类型
     * </pre>
     *
     * <code>optional .GroupType groupType = 4;</code>
     */
    public GroupType getGroupType() {
      GroupType result = GroupType.valueOf(groupType_);
      return result == null ? GroupType.UNRECOGNIZED : result;
    }

    public static final int ORGID_FIELD_NUMBER = 5;
    private int orgId_;
    /**
     * <pre>
     *归属组织机构
     * </pre>
     *
     * <code>optional int32 orgId = 5;</code>
     */
    public int getOrgId() {
      return orgId_;
    }

    public static final int MAXNUM_FIELD_NUMBER = 6;
    private long maxNum_;
    /**
     * <pre>
     *最大人数
     * </pre>
     *
     * <code>optional int64 maxNum = 6;</code>
     */
    public long getMaxNum() {
      return maxNum_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (groupId_ != 0) {
        output.writeInt32(1, groupId_);
      }
      if (!getGroupNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, groupName_);
      }
      if (!getAvatarBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, avatar_);
      }
      if (groupType_ != GroupType.GROUP_TYPE_UNKNOW.getNumber()) {
        output.writeEnum(4, groupType_);
      }
      if (orgId_ != 0) {
        output.writeInt32(5, orgId_);
      }
      if (maxNum_ != 0L) {
        output.writeInt64(6, maxNum_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (groupId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, groupId_);
      }
      if (!getGroupNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, groupName_);
      }
      if (!getAvatarBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, avatar_);
      }
      if (groupType_ != GroupType.GROUP_TYPE_UNKNOW.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, groupType_);
      }
      if (orgId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, orgId_);
      }
      if (maxNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, maxNum_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Group)) {
        return super.equals(obj);
      }
      Group other = (Group) obj;

      boolean result = true;
      result = result && (getGroupId()
          == other.getGroupId());
      result = result && getGroupName()
          .equals(other.getGroupName());
      result = result && getAvatar()
          .equals(other.getAvatar());
      result = result && groupType_ == other.groupType_;
      result = result && (getOrgId()
          == other.getOrgId());
      result = result && (getMaxNum()
          == other.getMaxNum());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId();
      hash = (37 * hash) + GROUPNAME_FIELD_NUMBER;
      hash = (53 * hash) + getGroupName().hashCode();
      hash = (37 * hash) + AVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getAvatar().hashCode();
      hash = (37 * hash) + GROUPTYPE_FIELD_NUMBER;
      hash = (53 * hash) + groupType_;
      hash = (37 * hash) + ORGID_FIELD_NUMBER;
      hash = (53 * hash) + getOrgId();
      hash = (37 * hash) + MAXNUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMaxNum());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Group parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Group parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Group parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Group parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Group parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Group parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Group parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Group parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Group parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Group parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Group prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.largehat.common.im.packets.Group}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.largehat.common.im.packets.Group)
        GroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GroupProto.internal_static_com_largehat_common_im_packets_Group_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GroupProto.internal_static_com_largehat_common_im_packets_Group_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Group.class, Builder.class);
      }

      // Construct using com.largehat.common.im.packets.GroupProto.Group.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        groupId_ = 0;

        groupName_ = "";

        avatar_ = "";

        groupType_ = 0;

        orgId_ = 0;

        maxNum_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GroupProto.internal_static_com_largehat_common_im_packets_Group_descriptor;
      }

      public Group getDefaultInstanceForType() {
        return Group.getDefaultInstance();
      }

      public Group build() {
        Group result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Group buildPartial() {
        Group result = new Group(this);
        result.groupId_ = groupId_;
        result.groupName_ = groupName_;
        result.avatar_ = avatar_;
        result.groupType_ = groupType_;
        result.orgId_ = orgId_;
        result.maxNum_ = maxNum_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Group) {
          return mergeFrom((Group)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Group other) {
        if (other == Group.getDefaultInstance()) return this;
        if (other.getGroupId() != 0) {
          setGroupId(other.getGroupId());
        }
        if (!other.getGroupName().isEmpty()) {
          groupName_ = other.groupName_;
          onChanged();
        }
        if (!other.getAvatar().isEmpty()) {
          avatar_ = other.avatar_;
          onChanged();
        }
        if (other.groupType_ != 0) {
          setGroupTypeValue(other.getGroupTypeValue());
        }
        if (other.getOrgId() != 0) {
          setOrgId(other.getOrgId());
        }
        if (other.getMaxNum() != 0L) {
          setMaxNum(other.getMaxNum());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Group parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Group) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int groupId_ ;
      /**
       * <pre>
       *群ID
       * </pre>
       *
       * <code>optional int32 groupId = 1;</code>
       */
      public int getGroupId() {
        return groupId_;
      }
      /**
       * <pre>
       *群ID
       * </pre>
       *
       * <code>optional int32 groupId = 1;</code>
       */
      public Builder setGroupId(int value) {
        
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群ID
       * </pre>
       *
       * <code>optional int32 groupId = 1;</code>
       */
      public Builder clearGroupId() {
        
        groupId_ = 0;
        onChanged();
        return this;
      }

      private Object groupName_ = "";
      /**
       * <pre>
       *群组名称
       * </pre>
       *
       * <code>optional string groupName = 2;</code>
       */
      public String getGroupName() {
        Object ref = groupName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          groupName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *群组名称
       * </pre>
       *
       * <code>optional string groupName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGroupNameBytes() {
        Object ref = groupName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          groupName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *群组名称
       * </pre>
       *
       * <code>optional string groupName = 2;</code>
       */
      public Builder setGroupName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群组名称
       * </pre>
       *
       * <code>optional string groupName = 2;</code>
       */
      public Builder clearGroupName() {
        
        groupName_ = getDefaultInstance().getGroupName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群组名称
       * </pre>
       *
       * <code>optional string groupName = 2;</code>
       */
      public Builder setGroupNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupName_ = value;
        onChanged();
        return this;
      }

      private Object avatar_ = "";
      /**
       * <pre>
       *群头像
       * </pre>
       *
       * <code>optional string avatar = 3;</code>
       */
      public String getAvatar() {
        Object ref = avatar_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          avatar_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *群头像
       * </pre>
       *
       * <code>optional string avatar = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarBytes() {
        Object ref = avatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          avatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *群头像
       * </pre>
       *
       * <code>optional string avatar = 3;</code>
       */
      public Builder setAvatar(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群头像
       * </pre>
       *
       * <code>optional string avatar = 3;</code>
       */
      public Builder clearAvatar() {
        
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群头像
       * </pre>
       *
       * <code>optional string avatar = 3;</code>
       */
      public Builder setAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        avatar_ = value;
        onChanged();
        return this;
      }

      private int groupType_ = 0;
      /**
       * <pre>
       *群类型
       * </pre>
       *
       * <code>optional .GroupType groupType = 4;</code>
       */
      public int getGroupTypeValue() {
        return groupType_;
      }
      /**
       * <pre>
       *群类型
       * </pre>
       *
       * <code>optional .GroupType groupType = 4;</code>
       */
      public Builder setGroupTypeValue(int value) {
        groupType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群类型
       * </pre>
       *
       * <code>optional .GroupType groupType = 4;</code>
       */
      public GroupType getGroupType() {
        GroupType result = GroupType.valueOf(groupType_);
        return result == null ? GroupType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *群类型
       * </pre>
       *
       * <code>optional .GroupType groupType = 4;</code>
       */
      public Builder setGroupType(GroupType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        groupType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群类型
       * </pre>
       *
       * <code>optional .GroupType groupType = 4;</code>
       */
      public Builder clearGroupType() {
        
        groupType_ = 0;
        onChanged();
        return this;
      }

      private int orgId_ ;
      /**
       * <pre>
       *归属组织机构
       * </pre>
       *
       * <code>optional int32 orgId = 5;</code>
       */
      public int getOrgId() {
        return orgId_;
      }
      /**
       * <pre>
       *归属组织机构
       * </pre>
       *
       * <code>optional int32 orgId = 5;</code>
       */
      public Builder setOrgId(int value) {
        
        orgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *归属组织机构
       * </pre>
       *
       * <code>optional int32 orgId = 5;</code>
       */
      public Builder clearOrgId() {
        
        orgId_ = 0;
        onChanged();
        return this;
      }

      private long maxNum_ ;
      /**
       * <pre>
       *最大人数
       * </pre>
       *
       * <code>optional int64 maxNum = 6;</code>
       */
      public long getMaxNum() {
        return maxNum_;
      }
      /**
       * <pre>
       *最大人数
       * </pre>
       *
       * <code>optional int64 maxNum = 6;</code>
       */
      public Builder setMaxNum(long value) {
        
        maxNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *最大人数
       * </pre>
       *
       * <code>optional int64 maxNum = 6;</code>
       */
      public Builder clearMaxNum() {
        
        maxNum_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.largehat.common.im.packets.Group)
    }

    // @@protoc_insertion_point(class_scope:com.largehat.common.im.packets.Group)
    private static final Group DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Group();
    }

    public static Group getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Group>
        PARSER = new com.google.protobuf.AbstractParser<Group>() {
      public Group parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Group(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Group> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Group> getParserForType() {
      return PARSER;
    }

    public Group getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_largehat_common_im_packets_Group_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_largehat_common_im_packets_Group_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Group.proto\022\036com.largehat.common.im.pa" +
      "ckets\032\nChat.proto\"y\n\005Group\022\017\n\007groupId\030\001 " +
      "\001(\005\022\021\n\tgroupName\030\002 \001(\t\022\016\n\006avatar\030\003 \001(\t\022\035" +
      "\n\tgroupType\030\004 \001(\0162\n.GroupType\022\r\n\005orgId\030\005" +
      " \001(\005\022\016\n\006maxNum\030\006 \001(\003B.\n\036com.largehat.com" +
      "mon.im.packetsB\nGroupProtoH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Chat.getDescriptor(),
        }, assigner);
    internal_static_com_largehat_common_im_packets_Group_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_largehat_common_im_packets_Group_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_largehat_common_im_packets_Group_descriptor,
        new String[] { "GroupId", "GroupName", "Avatar", "GroupType", "OrgId", "MaxNum", });
    Chat.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
