// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

package com.largehat.common.im.packets;

/**
 * <pre>
 *连接关闭原因
 * </pre>
 *
 * Protobuf enum {@code SessionCloseReason}
 */
public enum SessionCloseReason
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *超时退出
   * </pre>
   *
   * <code>NORMAL = 0;</code>
   */
  NORMAL(0),
  /**
   * <pre>
   *超时
   * </pre>
   *
   * <code>OVER_TIME = 1;</code>
   */
  OVER_TIME(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *超时退出
   * </pre>
   *
   * <code>NORMAL = 0;</code>
   */
  public static final int NORMAL_VALUE = 0;
  /**
   * <pre>
   *超时
   * </pre>
   *
   * <code>OVER_TIME = 1;</code>
   */
  public static final int OVER_TIME_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static SessionCloseReason valueOf(int value) {
    return forNumber(value);
  }

  public static SessionCloseReason forNumber(int value) {
    switch (value) {
      case 0: return NORMAL;
      case 1: return OVER_TIME;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SessionCloseReason>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SessionCloseReason> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SessionCloseReason>() {
          public SessionCloseReason findValueByNumber(int number) {
            return SessionCloseReason.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return Chat.getDescriptor()
        .getEnumTypes().get(6);
  }

  private static final SessionCloseReason[] VALUES = values();

  public static SessionCloseReason valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SessionCloseReason(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:SessionCloseReason)
}

