// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

package com.largehat.common.im.packets;

/**
 * <pre>
 *用户通知类型
 * </pre>
 *
 * Protobuf enum {@code UserNoticeType}
 */
public enum UserNoticeType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *上线
   * </pre>
   *
   * <code>USER_NOTICE_TYPE_ONLINE = 0;</code>
   */
  USER_NOTICE_TYPE_ONLINE(0),
  /**
   * <pre>
   *下线
   * </pre>
   *
   * <code>USER_NOTICE_TYPE_OFFLINE = 1;</code>
   */
  USER_NOTICE_TYPE_OFFLINE(1),
  /**
   * <pre>
   *分享
   * </pre>
   *
   * <code>USER_NOTICE_TYPE_SHARE = 2;</code>
   */
  USER_NOTICE_TYPE_SHARE(2),
  /**
   * <pre>
   *跟投
   * </pre>
   *
   * <code>USER_NOTICE_TYPE_BET = 3;</code>
   */
  USER_NOTICE_TYPE_BET(3),
  /**
   * <pre>
   *红包
   * </pre>
   *
   * <code>USER_NOTICE_TYPE_REDPACKAGE = 4;</code>
   */
  USER_NOTICE_TYPE_REDPACKAGE(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *上线
   * </pre>
   *
   * <code>USER_NOTICE_TYPE_ONLINE = 0;</code>
   */
  public static final int USER_NOTICE_TYPE_ONLINE_VALUE = 0;
  /**
   * <pre>
   *下线
   * </pre>
   *
   * <code>USER_NOTICE_TYPE_OFFLINE = 1;</code>
   */
  public static final int USER_NOTICE_TYPE_OFFLINE_VALUE = 1;
  /**
   * <pre>
   *分享
   * </pre>
   *
   * <code>USER_NOTICE_TYPE_SHARE = 2;</code>
   */
  public static final int USER_NOTICE_TYPE_SHARE_VALUE = 2;
  /**
   * <pre>
   *跟投
   * </pre>
   *
   * <code>USER_NOTICE_TYPE_BET = 3;</code>
   */
  public static final int USER_NOTICE_TYPE_BET_VALUE = 3;
  /**
   * <pre>
   *红包
   * </pre>
   *
   * <code>USER_NOTICE_TYPE_REDPACKAGE = 4;</code>
   */
  public static final int USER_NOTICE_TYPE_REDPACKAGE_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static UserNoticeType valueOf(int value) {
    return forNumber(value);
  }

  public static UserNoticeType forNumber(int value) {
    switch (value) {
      case 0: return USER_NOTICE_TYPE_ONLINE;
      case 1: return USER_NOTICE_TYPE_OFFLINE;
      case 2: return USER_NOTICE_TYPE_SHARE;
      case 3: return USER_NOTICE_TYPE_BET;
      case 4: return USER_NOTICE_TYPE_REDPACKAGE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<UserNoticeType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      UserNoticeType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<UserNoticeType>() {
          public UserNoticeType findValueByNumber(int number) {
            return UserNoticeType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return Chat.getDescriptor()
        .getEnumTypes().get(9);
  }

  private static final UserNoticeType[] VALUES = values();

  public static UserNoticeType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private UserNoticeType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:UserNoticeType)
}

