spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  freemarker:
    suffix:  .html
    request-context-attribute: request
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8000
  servlet:
    context-path: /largehat-admin


dubbo:
  application:
    id: largehat-server
    name: largehat-server
    qos-enable: true
    qos-accept-foreign-ip: false
    qos-port: 33333
  registry:
    id: registry-largehat
    address: zookeeper://localhost:2181
    check: false
    client: curator
  protocol:
    name: dubbo
    id: dubbo
    port: 20008
  metadata-report:
    address: zookeeper://localhost:2181


#定义服务版本信息
api:
  service:
    version: 1.0.0
    timeout: 30000

#jwt
jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间 2个小时
  expiration: 7200000
  auth:
    # 授权路径
    path: /login
    # 获取用户信息
    account: /info

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true

#是否开启 swagger-ui
swagger:
  enabled: true