server:
  port: 8989
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 1
    host: localhost
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）

#定义
netty:
  tcp:
    serverIp: 127.0.0.1
    port: 11111