server:
  port: 8989
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

  redis:
    database: 1
    host: localhost
    port: 6379
    password:        # 密码（默认为空）
    timeout: 6000   # 连接超时时长（毫秒）
    maxActive: 100   # 最大激活
    maxWait: 1000
    maxIdle: 100
    minIdle: 100


  #配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

#定义服务器启动信息
im:
  config:
    bindIp: 172.16.120.120
    bindPort: 11111
    heartbeatTimeout: 60
    isStore: true
    isCluster: true
    readBufferSize: 2048

